# Index of the /joy/button array which triggers Carrot Reference
carrot_index: 5

# Value at the /joy/button[carrot_index] which enables Carrot Reference
carrot_enable: 1

# Fame ID where the reference is published
carrot_frame_id: "world"

# If carrot land is false landing is done by asking Mavros to go to 'LAND' mode
# Otherwise, land mode is done by lowering the Carrot Reference
carrot_land: true

# If using 'carrot_land' this flag is able to automatically disarm the UAV when 
# landing is completed. This is needed if using thrust mode (GUID_OPTIONS=8)
land_disarm_enabled: true

# Speed at which the landing is performed (if carrot_land is true, 
# otherwise land speed is dictated by the autopilot)
land_speed: 0.3

# Initial reference step before the takeoff ramp during automatic takeoff
initial_takeoff_height: 0.1

# Speed at which the takeoff is performed after the initial step
takeoff_speed: 0.2
